// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_WUKROZdD5nhcNmgKAqPDvyPfhxe3J9A',
    appId: '1:438067928774:web:5bbdb90f57ea8d8b37c1c7',
    messagingSenderId: '438067928774',
    projectId: 'fruits-hub-bbd84',
    authDomain: 'fruits-hub-bbd84.firebaseapp.com',
    storageBucket: 'fruits-hub-bbd84.firebasestorage.app',
    measurementId: 'G-DS2V7XKEXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbdSxeyeTCqKVsN5jZ6lLCNscu4C8iNE',
    appId: '1:438067928774:android:33494935f05becfa37c1c7',
    messagingSenderId: '438067928774',
    projectId: 'fruits-hub-bbd84',
    storageBucket: 'fruits-hub-bbd84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBagoh7JNvtBuWsZPIQhpkVsYbXVfuw34E',
    appId: '1:438067928774:ios:61d238dd18a3d21237c1c7',
    messagingSenderId: '438067928774',
    projectId: 'fruits-hub-bbd84',
    storageBucket: 'fruits-hub-bbd84.firebasestorage.app',
    androidClientId: '438067928774-q1mo9v20vlbn7phqjg6jg43sicpg84au.apps.googleusercontent.com',
    iosClientId: '438067928774-4g633c2mte19ml5fjjn4du9a2einbnve.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_WUKROZdD5nhcNmgKAqPDvyPfhxe3J9A',
    appId: '1:438067928774:web:bb9e192221341e0f37c1c7',
    messagingSenderId: '438067928774',
    projectId: 'fruits-hub-bbd84',
    authDomain: 'fruits-hub-bbd84.firebaseapp.com',
    storageBucket: 'fruits-hub-bbd84.firebasestorage.app',
    measurementId: 'G-5FZ6SNDX9V',
  );
}
